### ISSUE TITLE
Ublock makes it crash

### ISSUE THREAD

**Issue by Antoine-O** [okgrow/analytics#138] opened 2016-10-12 19:17 UTC
Hello,

when Ublock is on Iron router crashes. I am on version 2.0.0 is there any fix ?

Thanks

**Comment by ghost** [comment] 2016-10-28 21:37
@Antoine-O We cannot reproduce this issue. When uBlock is enabled the plugin will be blocked from sending analytics data. But iron-router is not crashing. 

Could you provide a minimal working reproduction of the bug for us to take a look at?

**Comment by ghost** [comment] 2016-10-28 21:37
We will close this issue for now until we can reproduce it.

**Closed as completed by ghost** 2016-10-28 21:37 UTC
Labels: cant-reproduce

**Comment by ghost** [comment] 2016-10-28 21:48
@Antoine-O I think your issue may be because you aren't using the `--production` tag when running meteor locally. You need to use this for the analytics plugin to work correctly.

**Comment by arrygoo** [comment] 2016-10-28 22:13
^ https://github.com/okgrow/analytics#ad-blocker

**Comment by Antoine-O** [comment] 2016-10-29 08:19
Go on beta.quickcontest.com with ublock enabled it will certainly crash

Le sam. 29 oct. 2016 00:13, Aryan Goharzad notifications@github.com a
écrit :

**Comment by Antoine-O** [comment] 2016-10-29 10:05
I am.using a docker image abd i am not using meteor directly as it is 'exported' as a nide.js application. This may cause the problem ?

**Comment by Antoine-O** [comment] 2016-10-29 10:07
Fyi i am using https://github.com/CyCoreSystems/docker-meteor

**Comment by ghost** [comment] 2016-10-31 16:57
@Antoine-O The issue is that your code is not minified in the production deployment on the website you linked above. If you look inside the resources you can see all the individual files, this includes the name of the files. UBlock will block any files with the word analytics in the name and that is what is causing the crash. The --production tag minifies / bundles the codebase and fixes this issue. I'm not sure why the files aren't minified in production but this must be something to do with Docker. You need to change your production environment to bundle the code, this will probably be something in Docker that you need to configure.

**Comment by Antoine-O** [comment] 2016-11-02 22:51
you nailed it! I don't know why but "minified" packages were removed from the project :'(.
I'll give a try and close the issue if it is ok !
