### ISSUE TITLE
TypeError: Package['okgrow:analytics'] is undefined

### ISSUE THREAD

**Issue by nickredmark** [okgrow/analytics#176] opened 2017-05-09 13:02 UTC
After reinstalling meteor and my app on a new computer (ubuntu 16.04), the client renders a white screen, the console shows the following error:

```
TypeError: Package['okgrow:analytics'] is undefined
```

What causes the error is global-imports.js

```
/* Imports for global scope */

Mongo = Package.mongo.Mongo;
Session = Package.session.Session;
Tracker = Package.tracker.Tracker;
Deps = Package.tracker.Deps;
check = Package.check.check;
Match = Package.check.Match;
Reload = Package.reload.Reload;
ServiceConfiguration = Package['service-configuration'].ServiceConfiguration;
CollectionHooks = Package['matb33:collection-hooks'].CollectionHooks;
Security = Package['ongoworks:security'].Security;
Roles = Package['nicolaslopezj:roles'].Roles;
objectHasKey = Package['nicolaslopezj:roles'].objectHasKey;
_i18n = Package['universe:i18n']._i18n;
i18n = Package['universe:i18n'].i18n;
RouterAutoscroll = Package['okgrow:router-autoscroll'].RouterAutoscroll;
AccountsAnonymousAuto = Package['brettle:accounts-anonymous-auto'].AccountsAnonymousAuto;
AccountsAddService = Package['brettle:accounts-add-service'].AccountsAddService;
AccountsLogoutToSwitch = Package['brettle:accounts-logout-to-switch'].AccountsLogoutToSwitch;
LoginState = Package['brettle:accounts-login-state'].LoginState;
FlowRouter = Package['kadira:flow-router'].FlowRouter;
analytics = Package['okgrow:analytics'].analytics; // <-- the offending line
Meteor = Package.meteor.Meteor;
global = Package.meteor.global;
meteorEnv = Package.meteor.meteorEnv;
WebApp = Package.webapp.WebApp;
_ = Package.underscore._;
DDP = Package['ddp-client'].DDP;
meteorInstall = Package.modules.meteorInstall;
Buffer = Package.modules.Buffer;
process = Package.modules.process;
Symbol = Package['ecmascript-runtime'].Symbol;
Map = Package['ecmascript-runtime'].Map;
Set = Package['ecmascript-runtime'].Set;
meteorBabelHelpers = Package['babel-runtime'].meteorBabelHelpers;
Promise = Package.promise.Promise;
Accounts = Package['accounts-base'].Accounts;
Facebook = Package['facebook-oauth'].Facebook;
Google = Package['google-oauth'].Google;
Collection2 = Package['aldeed:collection2-core'].Collection2;
Autoupdate = Package.autoupdate.Autoupdate;
SimpleSchema = Package['aldeed:simple-schema'].SimpleSchema;
MongoObject = Package['aldeed:simple-schema'].MongoObject;
```

Relevant settings:

```
{
	"public": {
		"analyticsSettings": {
			"Google Analytics": {
				"trackingId": "UA-XXX"
			}
		},
	},
}
```

.meteor/packages:

```
meteor-base@1.0.4
mongo@1.1.17
session@1.1.7
tracker@1.1.3
check@1.2.5
email@1.2.1
shell-server@0.2.3
static-html
es5-shim@4.6.15
ecmascript@0.7.3
reload@1.1.11
accounts-password@1.3.6
accounts-facebook@1.1.1
accounts-google@1.1.2
service-configuration@1.0.11
aldeed:collection2
dburles:collection-helpers
matb33:collection-hooks
ongoworks:security
nicolaslopezj:roles
fortawesome:fontawesome
universe:i18n
okgrow:router-autoscroll
brettle:accounts-anonymous-auto
brettle:accounts-add-service
brettle:accounts-logout-to-switch
brettle:accounts-login-state
standard-minifier-css@1.3.4
standard-minifier-js@2.0.0
meteorhacks:aggregate
kadira:flow-router
okgrow:analytics
```

versions

```
accounts-base@1.2.17
accounts-facebook@1.1.1
accounts-google@1.1.2
accounts-oauth@1.1.15
accounts-password@1.3.6
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
allow-deny@1.0.5
autoupdate@1.3.12
babel-compiler@6.18.2
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.3.2
blaze-tools@1.0.10
boilerplate-generator@1.0.11
brettle:accounts-add-service@1.0.0
brettle:accounts-anonymous@0.3.1
brettle:accounts-anonymous-auto@0.3.5
brettle:accounts-login-state@0.0.4
brettle:accounts-logout-to-switch@0.4.2
brettle:accounts-multiple@0.3.1
brettle:workaround-issue-4331@0.0.4
brettle:workaround-issue-4862@0.0.3
brettle:workaround-issue-4970@0.0.4
caching-compiler@1.1.9
caching-html-compiler@1.1.2
callback-hook@1.0.10
check@1.2.5
dburles:collection-helpers@1.1.0
ddp@1.2.5
ddp-client@1.3.4
ddp-common@1.2.8
ddp-rate-limiter@1.0.7
ddp-server@1.3.14
deps@1.0.12
diff-sequence@1.0.7
ecmascript@0.7.3
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.2.1
es5-shim@4.6.15
facebook-oauth@1.3.0
fortawesome:fontawesome@4.7.0
geojson-utils@1.0.10
google-oauth@1.2.4
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.12
id-map@1.0.9
jquery@1.11.10
kadira:flow-router@2.12.1
livedata@1.0.18
localstorage@1.0.12
logging@1.1.17
matb33:collection-hooks@0.8.4
mdg:validation-error@0.2.0
meteor@1.6.1
meteor-base@1.0.4
meteorhacks:aggregate@1.3.0
meteorhacks:collection-utils@1.2.0
minifier-css@1.2.16
minifier-js@2.0.0
minimongo@1.0.23
modules@0.8.2
modules-runtime@0.7.10
mongo@1.1.17
mongo-id@1.0.6
mongo-livedata@1.0.12
nicolaslopezj:roles@2.6.4
npm-bcrypt@0.9.2
npm-mongo@2.2.24
oauth@1.1.13
oauth2@1.1.11
observe-sequence@1.0.16
okgrow:analytics@2.1.3
okgrow:router-autoscroll@0.1.8
ongoworks:security@2.1.0
ordered-dict@1.0.9
promise@0.8.8
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.8
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.3
spacebars@1.0.15
spacebars-compiler@1.1.2
srp@1.0.10
standard-minifier-css@1.3.4
standard-minifier-js@2.0.0
static-html@1.2.2
templating-tools@1.1.2
tracker@1.1.3
ui@1.0.13
underscore@1.0.10
universe:i18n@1.11.2
universe:utilities@2.3.3
url@1.1.0
webapp@1.3.15
webapp-hashing@1.0.9
```

I'm using meteor 1.4.4.2 and okgrow:analytics 2.1.3

**Comment by cfnelson** [comment] 2017-05-09 22:43
@nmaro I haven't seen the usage before for `global-imports.js`, I am curious to know what the usage for it is? Also where is this file located (client/server) as that may have an effect? What versions of meteor and `okgrow:analytics` did this work with in the past? 

If it has worked in the past then I would suggest rolling back as the latest version of analytics is designed for usage with `imports` and the way we `export` may be effecting your usage.

**Comment by dcantatore** [comment] 2017-05-13 01:21
I'm having the same issue on my local install, anything I can do to help trouble shoot? Same exact error. 

I pulled it from my install for now

**Comment by nickredmark** [comment] 2017-05-16 14:47
`global-imports.js` is part of the meteor client build. Strangely `okgrow:analytics` worked for the very same version, reinstalling meteor and the app on a new machine led to the problem.

**Comment by ghost** [comment] 2017-05-19 17:28
We are unable reproduce this problem with a brand new Meteor app and `okgrow:analytics` v2.1.3.
We are able to reproduce what looks like a similar problem with a brand new Meteor app and `okgrow:analytics` v3.0.0.

Can you verify if this is the full error message you're seeing:

```
Uncaught Error: Cannot find module 'babel-runtime/core-js/object/assign'
  at require (modules-runtime.js?hash=2b888cb…:133)
  at meteorInstall.node_modules.meteor.okgrow:analytics.node_modules.@okgrow.auto-analytics.dist.index.js (okgrow_analytics.js?hash=2fb5ab0…:186)
  at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
  at require (modules-runtime.js?hash=2b888cb…:130)
  at meteorInstall.node_modules.meteor.okgrow:analytics.node_modules.@okgrow.auto-analytics.index.js (okgrow_analytics.js?hash=2fb5ab0…:167)
  at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
  at Module.require (modules-runtime.js?hash=2b888cb…:130)
  at Module.Mp.importSync (modules.js?hash=3414565…:349)
  at meteorInstall.node_modules.meteor.okgrow:analytics.client.main.js (main.js:1)
  at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)

Uncaught TypeError: Cannot read property 'analytics' of undefined
    at global-imports.js?hash=51be4a0…:7 (anonymous) @ global-imports.js?hash=51be4a0…:7 app.js?hash=ac0a27d…:1 Uncaught ReferenceError: meteorInstall is not defined

Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=ac0a27d…:1
(anonymous) @ app.js?hash=ac0a27d…:1
```
Can you copy the full error your seeing.

**Comment by charlesdeb** [comment] 2017-05-19 20:52
I have got a similar error - although they look different between Chrome and Firefox on Win 10. In Chrome, the console shows me the following error, but still shows me the page I want (and I can see my page hits in real time on Google Analytics - so OKGrow is working to some extent):
```
Uncaught Error: Duplicate ReactiveDict name: activeRouteConfig
    at Function.ReactiveDict._registerDictForMigrate (migration.js:13)
    at new ReactiveDict (reactive-dict.js:25)
    at init (active.route.js:35)
    at meteorInstall.node_modules.meteor.ostrio:flow-router-extra.client._init.js (_init.js:20)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at ostrio_flow-router-extra.js?hash=a3344d5…:3979
    at ostrio_flow-router-extra.js?hash=a3344d5…:3985
```
No mention here of OKGrow errors. However, FF doesn't show me the page I want (it runs into routing errors), hence there are no hits on Google Analytics and on the console in FF I see:
```
Error: Duplicate ReactiveDict name: activeRouteConfig  reactive-dict.js:292:60
	migration.js/ReactiveDict._registerDictForMigrate http://localhost:3000/packages/reactive-dict.js:292:60
	ReactiveDict http://localhost:3000/packages/reactive-dict.js:70:7
	init http://localhost:3000/packages/ostrio_flow-router-extra.js:196:16
	require<.node_modules.meteor["ostrio:flow-router-extra"].client["_init.js"]< http://localhost:3000/packages/ostrio_flow-router-extra.js:120:21
	fileEvaluate http://localhost:3000/packages/modules-runtime.js:207:9
	require http://localhost:3000/packages/modules-runtime.js:130:16
	<anonymous> http://localhost:3000/packages/ostrio_flow-router-extra.js:3979:15
	<anonymous> http://localhost:3000/packages/ostrio_flow-router-extra.js:11:2
TypeError: Package['okgrow:analytics'] is undefined[Learn More]  global-imports.js:22:1
	<anonymous> http://localhost:3000/packages/global-imports.js:22:1
ReferenceError: meteorInstall is not defined[Learn More]  app.js:1:5
	<anonymous> http://localhost:3000/app/app.js:1:5
```
This error is closer to the ones reported above: the OKGrow undefined error from @nmaro and meteorInstall is not defined from @ccuilla . Note that I added the ostrio_flow-router-extra package in order set the document.title for each page which OKGRow needs. Before installing OKGrow v3.00, I was having no issues. I can send you my package list as well if that helps. In a nutshell I am running meteor 1.4.4.2 on Win 10. I could try uninstalling the ostrio_flow-router stuff too if that helps.
EDIT: Upon further research, much of my issue seems to be related to problems with the ostrio_flow-router-extra clashing with another package. Once I have resolved them, I will retest OKGrow.

**Comment by u-rogel** [comment] 2017-05-20 16:38
If it helps, this is the error I am getting:

```
modules-runtime.js?hash=2b888cb…:133
Uncaught Error: Cannot find module 'babel-runtime/core-js/object/assign'
    at require (modules-runtime.js?hash=2b888cb…:133)
    at meteorInstall.node_modules.meteor.okgrow:analytics.node_modules.@okgrow.auto-analytics.dist.index.js (okgrow_analytics.js?hash=2fb5ab0…:186)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at require (modules-runtime.js?hash=2b888cb…:130)
    at meteorInstall.node_modules.meteor.okgrow:analytics.node_modules.@okgrow.auto-analytics.index.js (okgrow_analytics.js?hash=2fb5ab0…:167)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
    at Module.require (modules-runtime.js?hash=2b888cb…:130)
    at Module.Mp.importSync (printer.js:170)
    at meteorInstall.node_modules.meteor.okgrow:analytics.client.main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=2b888cb…:207)
global-imports.js?hash=b82c459…:20 
Uncaught TypeError: Cannot read property 'analytics' of undefined
    at global-imports.js?hash=b82c459…:20
app.js?hash=013db20…:1
Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=013db20…:1
kadira_flow-router.js?hash=053cdc0…:519 
There is no route for the path: /

```

I use windows 7 64-bit, meteor-1.4.4.2, .okgrow:analytics 3.0.0

**Comment by SimonatoLucaManuele** [comment] 2017-05-23 17:37
If it helps, I am getting the same @cowCrazy error both in MacOs Sierra and DigitalOcean Ubuntu 16.04

**Comment by cfnelson** [comment] 2017-05-24 22:45
**TEMP SOLUTION**: Please use `okgrow:analytics@2.1.3`, e.g (`meteor add okgrow:analytics@2.1.3`).

We have been unable to reproduce the error on `v2.1.3`. The latest version `v3.0.0` does have the bug above which we will work at resolving asap. PR's are encouraged.

**Comment by virtuman** [comment] 2017-05-29 19:10
same here on ubuntu 16.04 and centos7 linuxes

**Comment by ghost** [comment] 2017-06-09 17:00
Please try version 3.0.1. We believe this fixes this issue.

@SimonatoLucaManuele @virtuman @cowCrazy @charlesdeb @nmaro @dcantatore

**Comment by v3rron** [comment] 2017-06-12 02:37
Still having an issue, when deploying with `mup` on clean staging **Ubuntu 16.04** server. Currently `versions` file says that I'm using `okgrow:analytics@3.0.1`. Here's the error from the client:
```
GET https://staging.app.com/packages/okgrow_analytics.js?hash=897b8f4a016c8d333e9e7d97669e73fb4a0d41de net::ERR_BLOCKED_BY_CLIENT

global-imports.js?hash=0a3d9b8…:28 Uncaught TypeError: Cannot read property 'analytics' of undefined
    at global-imports.js?hash=0a3d9b8…:28
(anonymous) @ global-imports.js?hash=0a3d9b8…:28
app.js?hash=303ee88…:1 

Uncaught ReferenceError: meteorInstall is not defined
    at app.js?hash=303ee88…:1
(anonymous) @ app.js?hash=303ee88…:1

kadira_flow-router.js?hash=9499575…:518 There is no route for the path: /
```
**UPDATE**: even after downgrading to 2.1.3, still facing the same issue so I had to uninstall it for my server to start working again.

**Comment by ghost** [comment] 2017-06-16 14:36
Fixed with version 3.0.1.

**Closed as completed by ghost** 2017-06-16 14:36 UTC
Labels: bug, pull-request-encouraged, confirmed, fixed

**Comment by qutehoot007** [comment] 2018-05-04 23:47
Hi, I have the same issue but found this is related to AdBlock chrome extension, try to disable it and check again.

**Comment by Gwened** [comment] 2018-10-20 17:32
I got the same issue (on 2.1.3) after installing the Windscribe Chrome extension.
Disabling it fixed the issue!
