### ISSUE TITLE
analytics not defined

### ISSUE THREAD

**Issue by nickredmark** [okgrow/analytics#44] opened 2015-07-27 20:34 UTC
```
meteor list
...
okgrow:analytics               0.3.0  Complete Google Analytics, Mixpanel, KISSmetrics (and more) integration for Meteor
...

meteor --version
Meteor 1.1.0.2
```

settings.json contains

```
{
    "public": {
        ....
        "analyticsSettings": {
            "Google Analytics": {"trackingId": "XXXXX"}
        }
    },
    ...
}
```

I start meteor with

```
meteor --settings config/settings.json
```

no error messages

when I start

```
meteor shell
```

and type

```
analytics.debug()
```

I get

```
ReferenceError: analytics is not defined
```

**Comment by tsemana** [comment] 2015-07-27 20:38
It is (currently) a client-side tool. What happens when you go into the browser console and type `analytics.debug()`?

**Comment by nickredmark** [comment] 2015-07-27 21:19
Just the same
ReferenceError: analytics is not defined

**Comment by tsemana** [comment] 2015-07-27 21:41
Last test: what happens when you start the app with just `meteor`.  You would normally get a console log saying `"Missing analyticsSettings in Meteor.settings.public"`.

If not, would it be possible to invite me to your repo, or are you able to create a base app that reproduces the problem?

**Comment by nickredmark** [comment] 2015-07-28 08:15
I removed the analytics settings from the config, and it doesn't complain.

I tried something else:

   meteor create test
   cd test
   meteor add okgrow:analytics
   meteor

No error message. Then I added the above settings file

```
meteor --settings config/settings.json
```

No error message, no analytics object.

Weird.

**Comment by tsemana** [comment] 2015-07-28 12:10
Could you post the repo and give me access?

**Comment by tsemana** [comment] 2015-07-28 12:40
@nicolamr here's a base repo I created https://github.com/tsemana/analytics-test.
Starting this app with `meteor` (without a `settings.json` file), going to app in the browser and opening the javascript console (alt+command j in chrome on a mac), I immediately see `Missing analyticsSettings in Meteor.settings.public`. 
Typing `analytics` into the javascript console on the browser also returns the analytics object.
If that's not what you're getting on your bare repo, please post it and give me the link.

**Comment by nickredmark** [comment] 2015-07-28 12:42
Here's the one that doesn't work with me, going to try yours.
https://github.com/nicolamr/okgrow-analytics-test
It feels like I'm doing some stupid mistake.

**Comment by nickredmark** [comment] 2015-07-28 12:47
I cloned your repo and it doesn't work with me:

![analytics](https://cloud.githubusercontent.com/assets/574453/8931553/7b822304-3537-11e5-8ce9-2e19ea5aa850.png)

**Comment by nickredmark** [comment] 2015-07-28 12:50
Tested both on my local machine (ubuntu) and my server (debian), no analytics.

**Comment by tsemana** [comment] 2015-07-28 12:53
That's baffling. I cloned your repo and it worked for me:

![screen shot 2015-07-28 at 8 50 11 am](https://cloud.githubusercontent.com/assets/573540/8931683/0f74fbcc-3506-11e5-9853-fb40f19ca12f.png)

**Comment by nickredmark** [comment] 2015-07-28 12:57
Completely reinstalled meteor, still nothing.

**Comment by nickredmark** [comment] 2015-07-28 13:06
I tried on a completely fresh meteor install on a friend's laptop and it works.

**Comment by tsemana** [comment] 2015-07-31 13:45
@nicolamr - any progress on your issue?

**Comment by tsemana** [comment] 2015-08-07 14:29
@nicolamr - this sounds like an environment-specific issue. Closing it for now.

**Closed as completed by tsemana** 2015-08-07 14:29 UTC

**Comment by nickredmark** [comment] 2015-08-07 15:41
Yeah, sorry, didn't get to look back into it yet. I'll check if 
analytics works with other modules first.
Thanks for your help.

**Comment by natecox** [comment] 2015-11-20 06:08
I'm having the same issue. Installed the package and analytics is not defined. No data is being pushed to google analytics, either.

**Comment by pauldowman** [comment] 2015-12-17 02:11
@natecox Did you get it figured out? Or can you provide us with a way to reproduce it?

**Comment by cellulosa** [comment] 2016-02-08 00:20
Same here. I'm running meteor as a service configured via `/etc/systemd/system/meteor.service`:

```
[Unit]
Description=nodejs daemon
After=network.target remote-fs.target

[Service]
User=root
ExecStart=/usr/bin/node /home/root/www/main.js
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=Meteor
Environment=ROOT_URL=http://website.com
Environment=PORT=3000
Environment=NODE_ENV=production
Environment=MONGO_URL=mongodb://127.0.0.1:27017/meteor
Environment=METEOR_SETTINGS={"public": {"analyticsSettings": {"Google Analytics" : {"trackingId": "UA-00000000"}}}}

[Install]
WantedBy=multi-user.target
```

Any idea?

**Comment by cellulosa** [comment] 2016-02-08 12:17
I fixed it removing the `METEOR_SETTINGS` line and using [commerce:env-settings](https://github.com/4commerce-technologies-AG/meteor-package-env-settings)

**Comment by littlemercury** [comment] 2016-06-04 14:58
@pauldowman @tsemana 
I have the same issue. Everything works fine on my remote host but doesn't work on Safari on my localhost. 
Strangely enough the issue is only on safari. Works fine on localhost with Chrome.
Same settings file and same code on both hosts. Works fine on the remote host with safari.
Seems to be an issue on safari with localhost for me.

**Comment by littlemercury** [comment] 2016-06-04 21:44
@pauldowman @tsemana - got it. My adblocker on safari was activated by the analytics code, and for some reason caused the analytics variable error. 
Disabling the adblocker for my site fixed the issue, though I'm not sure exactly why it would have caused the variable to not initialize.
I'm using Adblock Plus (adblockplus.org) for anyone else who is experiencing this issue.
