### ISSUE TITLE
Iron Router EnsureSignedIn Issue?

### ISSUE THREAD

**Issue by dcworldwide** [okgrow/analytics#18] opened 2015-04-28 01:33 UTC
Hi, i'm using your plugin with IR and the Accounts Core [EnsureSignedIn](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#content-protection) plugin. In my instance of okgroup:analytics, i've noticed that every router interaction seems to send a 'signedIn' track event to mixpanel. The result is that in my mixpanel event log, i'm seeing a large volume of signedIn events (shown below) repeatedly displayed whenever a route changes. Is this by design? 

![screen shot 2015-04-28 at 11 23 45](https://cloud.githubusercontent.com/assets/4898751/7361350/20927c8a-ed9a-11e4-8767-2a450c492aea.png)

**Comment by tsemana** [comment] 2015-04-30 00:58
@dcworldwide thanks for submitting this. It's not by design so we'll be looking into it.

**Comment by andreipopovici** [comment] 2015-04-30 06:06
+1 I'm getting the exact same thing, Identify + Track, when using useraccounts:core and Iron Router with EnsureSignedIn.

Any suggestions for a potential solution?

**Comment by andreipopovici** [comment] 2015-04-30 07:04
For my needs, I've added https://github.com/revolution-labs/meteor-user-login-state as a weak dependency, as well as checks for 'user.profile.registeredEmails' for compatibility with accounts-meld.

Not sure if such heavy modifications call for a pull request to this repo, your call.

**Comment by levino** [comment] 2015-05-02 10:23
+1 Happening for us at coyno.com too. We are using ensuresignedin too.

**Comment by andreipopovici** [comment] 2015-05-02 11:12
@Levino, here's my hacky fix, in case it's useful:

(uses the original getUserEmail() function from this repo)

``` javascript
trackLogins = function () {
  if (Meteor.user) {
    if (Meteor.user()) {
      trackSignIn();
    }
    if (!Meteor.user()) {
      trackSignOut()
    }
  }
};

trackSignIn = function(){
  var user = Meteor.user();
  if (user) {
    var userEmail = getUserEmail();
    if(userEmail){
      analytics.identify(user._id, {email: userEmail});
    }else{
      analytics.identify(user._id);
    }

    analytics.track("Signed in");
  }
}

trackSignOut = function(){
  analytics.track("Signed out");
}

if (Package['iron:router']) {
  Package['iron:router'].Router.onRun(function() {
    analytics.page(this.route.getName());
    this.next();
  });
}

Meteor.startup(function () {
  if(Package['revolutionlabs:user-login-state']){
    UserLoginState.onLogin = trackSignIn;
    UserLoginState.onLogout = trackSignOut;
    UserLoginState.init();
  }else{
    Tracker.autorun(trackLogins);
  }
});
```

**Comment by tsemana** [comment] 2015-05-05 12:00
@andreipopovici thanks for posting your workaround. Please feel free to try a first cut at a PR on it.

**Comment by pauldowman** [comment] 2015-05-05 18:03
It looks to me like this is actually an issue where `trackLogins()` could be re-run reactively as the user subscription loads, so I don't think it's related to the EnsureSignedIn plugin. (Unless I'm misunderstanding something.)

I think a simpler fix is just checking for `Meteor.userId` instead of `Meteor.user`. That doesn't change reactively. So make sure there's nothing inside `trackLogins()` that will change reactively as data loads. So `getUserEmail()` should be done outside the autorun.

**Comment by tsemana** [comment] 2015-05-11 03:02
@andreipopovici, @dcworldwide 
I haven't merged the PR yet, because I wanted to be absolutely sure I understood what was going on..  In the end, I'm not able to see the multiple singedIn events on a basic app using accounts and ensureSignedIn.

Could you tell me if you were using the latest version of the package(v0.2.3)? and if not what happens if you update to the new package?

If you are using the latest, could you take a look at the basic app I've setup here: https://github.com/okgrow/analytics-test-basic. This app is using iron:router / user-accounts, with ensureSignedIn for the topSecret and userProfile routes in the navbar.  When I navigate through app's routes via the navbar I don't get the double-signed-in events.

Thanks for your help on this. Please let me know what I've missed!

**Comment by tsemana** [comment] 2015-05-11 21:28
@andreipopovici, @dcworldwide, @Levino,

Please note also, we've just published an update to 0.2.4. Please give that version a try and let me know if the issue still exists.

**Comment by levino** [comment] 2015-05-12 07:18
@tsemana Thanks. Will do.

**Comment by pauldowman** [comment] 2015-05-18 18:51
I'm assuming this is fixed, I think it was due to the use of `onBeforeAction` instead of `onRun` which has been fixed. Please re-open it if you're still having an issue with the latest version.

**Closed as completed by pauldowman** 2015-05-18 18:51 UTC
Labels: bug
