### ISSUE TITLE
Events are not sent if "analytics.track" is called inside router

### ISSUE THREAD

**Issue by by-code** [okgrow/analytics#152] opened 2017-01-31 06:50 UTC
Following code won't track an event and won't even leave any error or debug information:
```
FlowRouter.route('/get-app', {
  action() {
    analytics.track('Download app 2', {  // Event is ignored
      category: 'Test',
      label: 'hello'
    });
});
```
while if I put tracking later in event loop it'll work correctly:
```
FlowRouter.route('/get-app', {
  action() {
    setTimeout(function() {
      analytics.track('Download app', {  // Event is tracked
        category: 'Test',
        label: 'hello'
      });
    }, 0);
});
```

**Comment by ghost** [comment] 2017-02-03 14:46
I'm currently unable to reproduce this issue on our latest version.

The first thing I'd like to confirm is if you are using our very latest version of this package. If not which version are you using?

**Comment by by-code** [comment] 2017-02-11 22:26
I'm using version 2.1.0. Here is the list of all my dependencies:
<img width="818" alt="screen shot 2017-02-11 at 2 18 36 pm" src="https://cloud.githubusercontent.com/assets/24600107/22857983/fc83ee52-f065-11e6-8100-021fc45ea113.png">

**Comment by by-code** [comment] 2017-02-11 23:26
I've created a simple app to demonstrate the issue. Please take a look: https://github.com/yan-gethello/okgrow-analytics-issue-demo

**Comment by ghost** [comment] 2017-02-17 16:38
Great. Thanks for the demo. It looks like there might be an issue where analytics isn't "ready" in the direct call.

One way to solve this is to do the following:

```analytics.ready(()` => analytics.track.apply(this, args));```

In your example specifically:

```
analytics.ready(()` => analytics.track.apply(this, 'How about this event', {
  category: 'Will it work?',
  label: 'or not'
}));
```

You can do that in the short-term.

We actually have some internal helpers that do exactly this (`trackEventWhenReady`, `trackPageWhenReady`, `identifyWhenReady`) that are not being exported. That's an oversight and will be fixed in a new patch release coming very shortly.

Sorry for the inconvenience.

**Comment by ghost** [comment] 2017-02-17 21:44
Version 2.1.1 published exporting helper functions that use analytics.ready() to ensure the underlying analytics package is ready to go. Should solve this issue.

**Closed as completed by ghost** 2017-02-17 21:44 UTC
Labels: bug, cant-reproduce, question, in-progress
