### ISSUE TITLE
Pageviews not tracked with FlowRouter SSR

### ISSUE THREAD

**Issue by ldelaporte** [okgrow/analytics#139] opened 2016-10-22 18:36 UTC
After implementing FlowRouter SSR page views are not tracked anymore (both Mixpanel & GA).

Without SSR it works fine. The debug logs show the initialization of both modules (Mixpanel & GA) and event tracking, however, there seems to be a problem with defining the FlowRouter.triggersEnter function.

I have assumed that triggersEnter cannot be defined as Package["kadira:flow-router-ssr"] in routers.js seems to be unavailable on startup. Nevertheless, a quick check without SSR showed the same (and it worked). I can't really figure out when Package["kadira:flow-router-ssr"].FlowRouter becomes available and how triggersEnter is initialized.

Thanks for your help!

**Comment by ldelaporte** [comment] 2016-10-24 08:21
The problem must be caused by initializing FlowRouter before Meteor.startup(), potentially in #123 

I was able to temporarily fix the issue by wrapping the initialization in a function and handing over a FlowRouter instance in Meteor.startup() instead of getting it from routers.js.

startup.js

``` js
import { initFlowRouter } from "./flow-router";

Meteor.startup(() => {
  if (SETTINGS) {
    initIronRouter();
    initFlowRouter(FlowRouter);
    ...
```

flow-router.js

``` js
const initFlowRouter = function(_FlowRouter) {
  ...
}
export {initFlowRouter};
```

**Comment by ghost** [comment] 2016-10-28 22:04
@ldelaporte We have been unable to reproduce this using the package's flow-router example (using flow-router-ssr). What version of flow-router-ssr are you using? And what version of this package?

Could you please provide a minimal working reproduction in the flow router example (this package).

**Comment by ghost** [comment] 2016-11-01 19:43
@ldelaporte I'm going to close this issue for now. We will re-open it once a minimal working reproduction is provided. Thanks.

**Comment by pauldowman** [comment] 2016-11-09 04:21
This might be fixed by #143.

**Comment by pauldowman** [comment] 2016-11-09 04:21
@ldelaporte as a temporary workaround try moving `okgrow:analytics` to the bottom of your `.meteor/packages` file. (That's not a real fix and might not always work).

**Comment by ldelaporte** [comment] 2016-11-20 14:11
@pauldowman  sorry for the delayed response - works fine!

**Comment by pauldowman** [comment] 2016-11-21 13:01
Thanks @ldelaporte. I assume you mean the workaround. #143 was merged and should be released today.

**Comment by ldelaporte** [comment] 2016-11-22 19:54
I tried #143 by cloning it locally :) Thanks for the release!

**Closed as completed** 2016-12-02 20:08 UTC
Labels: bug, fixed
