### ISSUE TITLE
Sign up event

### ISSUE THREAD

**Issue by mariagandica** [okgrow/analytics#172] opened 2017-04-28 20:45 UTC
Hello,
I'm using VulcanJs to create my app and I added the analytics, I'm using Mixpanel.

With the configuration, I got working the basic events: loaded a page and sign in. My problem is the sign up event, I got this error:

<img width="1057" alt="screen shot 2017-04-28 at 3 39 26 pm" src="https://cloud.githubusercontent.com/assets/9203095/25546487/ee13c7da-2c28-11e7-9597-c5531cbb96b6.png">

And, of course, the event is not sent.

Any hints?

**Comment by cfnelson** [comment] 2017-04-28 22:36
@mariagandica We only track the sign in/sign out event which is mentioned in our readme [here](https://github.com/okgrow/analytics#log-signinsignout). 

The error message you have provided doesn't provide much insight for us to help you. Our package doesn't invoke `createUser` or track the sign-up event. 

The stack trace doesn't contain any mention of our analytics package. Can you provide more details as to why you believe our analytics package is the cause for the error?

Closing the issue but will be happy to re-open if it is determined that the package has a bug.

**Closed as completed by cfnelson** 2017-04-28 22:36 UTC
Labels: question

**Comment by mariagandica** [comment] 2017-04-28 23:59
The problem is when I use "analytics.track" in CustomCallbacks, it says that it's undefined

**Comment by cfnelson** [comment] 2017-04-29 00:18
@mariagandica Can you provide a gist or a minimal working reproduction of your bug. Otherwise it is hard to help you. You can check out the [examples](https://github.com/okgrow/analytics/tree/master/examples) to see how you can use the analytics package. If `analytics` is undefined then you should make sure that you have correctly imported and instantiated it.
