### ISSUE TITLE
v2.1.1 does not work because of fsevents only used on Mac

### ISSUE THREAD

**Issue by micktaiwan** [okgrow/analytics#159] opened 2017-03-16 13:14 UTC
Version 2.1.1 breaks on Windows.
It depends on fsenvents and does not find binaries.

momentjs had the same problem
https://github.com/meteor/meteor/issues/7958

**Comment by pauldowman** [comment] 2017-03-16 13:30
Is this when adding the atmosphere package to a Meteor app? I can see that the `package.json` has `nodemon` in `devDependencies`, but `package.json` shouldn't even be used in that case.

`package.js` is the only thing that would bring in dependencies to a Meteor app and I don't see anything in there that would use fsevents.

**Comment by ddaydd** [comment] 2017-03-16 13:41
yes from atmosphere.

**Comment by cfnelson** [comment] 2017-03-17 17:45
@micktaiwan @ddaydd What version of Windows, Meteor and Router (flow router, iron router, react router) are you running? Does v2.1.3 work for you?

I have tested the okgrow:analytics@2.1.3 using the react-router example on Windows 7 and have been unable to reproduce.

**Comment by cfnelson** [comment] 2017-03-17 18:29
@micktaiwan @ddaydd I have tested on v2.1.1 and was able to reproduce the bug you have. The bug was resolved in v2.1.2 when we updated Meteor to 1.4.3.2 and removed router dependencies in our package.js

You should be able to resolve your issue by updating to v2.1.3 if it is an issue with our package. Otherwise you may be required to update Meteor to v1.4.3.2 to resolve the bug.

**Closed as completed by cfnelson** 2017-03-17 18:29 UTC
Labels: bug, fixed
